### ISSUE TITLE
Need some clarification regarding instructions for use

### ISSUE THREAD

**Issue by worldheadquarters** [thexmanxyz/Owl-Carousel-Neo-Gantry#1]
In the instructions (Joomla) you say to "Install it over the Joomla Plugin System.".  I am new to Joomla and Gantry 5  and am not sure what that means.  Do you mean to copy the files over existing files somewhere or is there an install mechanism/procedure that should be followed?

**Comment by thexmanxyz** [comment]
@worldheadquarters Sorry for the delay I completely missed your issue (oversaw the GitHub mail for some reason). Installing over the Joomla Plugin System means that you can install this Particle directly via the Joomla Plugin System as you would do with other Joomla Plugins. Simply upload one of these files:

![grafik](https://user-images.githubusercontent.com/17965908/73158739-08f23180-40e5-11ea-8e17-7c27bd8e9a9f.png)

via the Joomla backend. You find that under **Extensions** -> **Manage** -> **Install**. Then select the Plugin Package you want to install. Please download the package you need. If you use the Template `Hydrogen` or `Helium` choose one of those downloads. If you use another Gantry 5 Theme use the `Global` version. If you want to be on the save side. Always choose the `Global` package this will work for all Gantry 5 templates.

After installing over the Plugin System follow the instructions [here](https://github.com/thexmanxyz/Owl-Carousel-Neo-Gantry#automatic-installation-joomla-only). Please visit also [this link](http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet) directly from Gantry 5 it should guide you in the right direction in completing the install process. It explains how you modify and create the `custom.scss` file.
